name: $LANDO_APP_NAME
recipe: laravel

config:
  via: apache:2.4
  webroot: www/public
  php: 7.4
  xdebug: false
  database: mysql:5.7
  config:
    php: config/php/php.ini
    database: config/mysql/my.cnf

services:
  appserver:
    type: php:7.4
    via: apache:2.4
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
    xdebug: true
    config:
      php: config/php/php.ini
      database: config/mysql/my.cnf
    webroot: www/public
    build_as_root:
      - chmod +x "/app/services/appserver/build_as_root.sh" && /bin/sh /app/services/appserver/build_as_root.sh
    #run_as_root:
      #- chmod +x "/app/services/appserver/run_as_root.sh" && /bin/sh /app/services/appserver/run_as_root.sh
          
tooling:
  new-project:
    service: appserver
    user: root
    description: Creates a brand new Laravel project
    cmd:
      # - rm -rf /app/www       # should i remove any existing folder first? what about the code ?
      - composer create-project laravel/laravel www
      # - laravel new www --auth  # include auth
      
  db-backup:
    service: database
    user: root
    description: Creates a database backup
    cmd:
      - echo "Dumping $LANDO_APP_NAME database..."
      - mkdir -p /app/sql && /helpers/sql-export.sh /app/sql/dump.sql

